---
title: "Final 241 Project: Power Analysis"
author: "Arisa Nguyen, Annie Vellon, Samuel Omosuyi"
date: "10/4/2022"
name: ""
output: 
  pdf_document: 
    number_sections: true
---
```{r global options, include = FALSE}
knitr::opts_chunk$set(include = FALSE, message = FALSE, warning = FALSE )

knitr::knit_engines$set(problem_description = function(options) {
  code <- paste(options$code, collapse = "\n")
})

knitr::opts_chunk$set(tidy.opts = list(width.cutoff = 60), tidy = TRUE)
```

```{r package loads, warning=FALSE, message=FALSE}
library(data.table)
library(sandwich)
library(lmtest)

library(ggplot2)
library(knitr)

library(formatR)
```

```{r}
#TEST DATA, TO BE REPLACED WITH SYNTHETIC DATA 

library(data.table)
library(magrittr)

d <- fread('practice_data/list_data_2019.csv')
```

```{r}
# Scenario #1: Different sample sizes, 50/50 split for control and treatment 
size_to_sample <- seq(20, 200, by = 20)

power_values <- rep(NA, length(size_to_sample)) 

for(per in 1:length(size_to_sample)){
  t_test_p_values <- rep(NA, 1000) 
  for(i in 1:1000){
    d_treat = d[d$uniform_price_auction == 1]
    d_cont = d[d$uniform_price_auction == 0]
  
    d_comb = rbind(d_treat[sample(nrow(d_treat), size = size_to_sample[per]/2, replace = TRUE), ],
                 d_cont[sample(nrow(d_cont), size = size_to_sample[per]/2, replace = TRUE), ])
  
    t_test_ten_people <- d_comb[, t.test(bid ~ uniform_price_auction)]
    
    t_test_p_values[i] = t_test_ten_people$p.value
  }
  power_values[per] <- mean(t_test_p_values < 0.05)
  }

```

```{r}
# Creating dataframes for each scenario for plotting purposes
df1 = data.frame(size_to_sample, power_values)
df2 = data.frame(size_to_sample + 1, power_values + 0.001) #TO BE REPLACED with values from Sam
df3 = data.frame(size_to_sample + 2, power_values + 0.01) #TO BE REPLACED with values from Annie
```

```{r}
# Graphing power for each scenario 
names(df1) <- c("sample_size", "power")
names(df2) <- c("sample_size", "power")
names(df3) <- c("sample_size", "power")

#Plot data and specify the manual scale
dat <- rbind(df1,df2,df3)
dat$grp <- rep(factor(1:3),times=c(nrow(df1),nrow(df2),nrow(df3)))

ggplot(data = dat, aes(x = sample_size, y = power, colour = grp)) + 
    geom_line() +
    ggtitle("Power vs Sample Size") +
    labs(y = "Power", x = "Sample Size") +
    scale_color_discrete(name = "Scenario")
```

